version: '3.5'

services:

  master-node:
    image: babobka/node-project-master:1.0
    container_name: master-host
    env_file:
      - .env_master
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    networks:
      - node-project

  slave-node-1:
    image: babobka/node-project-slave:1.0
    container_name: slave-host-1
    env_file:
      - .env_slave
    environment:
      - WAIT_HOSTS=master-host:19090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    depends_on:
      - master-node
    networks:
      - node-project

  submaster-slave-node:
    image: babobka/node-project-slave:1.0
    container_name: submaster-slave-host
    env_file:
      - .env_submaster_slave
    environment:
      - WAIT_HOSTS=submaster-host:29090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    depends_on:
      - submaster-node
    networks:
      - node-project

  submaster-node:
    image: babobka/node-project-submaster:1.0
    container_name: submaster-host
    env_file:
      - .env_submaster
    environment:
      - WAIT_HOSTS=master-host:19090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=3
    volumes:
      - ../logs:/logs
      - ../tasks:/tasks
    depends_on:
      - master-node
    networks:
      - node-project

networks:
  node-project:
